### ISSUE TITLE
Create a list of all relevant SSDF controls and map SAMM 2.0 practices to it

### ISSUE THREAD

**Issue by SebaDele** [owaspsamm/core#106] opened 2022-11-06 09:19 UTC
As a contributor I would like to have the list of SSDF controls in scope so that we can map the appropriate SAMM practices or activity to it.

Acceptance criteria:

-  the controls are in the proper format (yaml, csv, json, ???)
-  each SSDF control is represented in a proper, reusable format (TBD)

**Comment by johnellingsworth** [comment] 2022-12-20 21:00
Closing as this is a dupe of https://github.com/owaspsamm/samm-suite/issues/10

**Closed by johnellingsworth** 2022-12-20 21:00 UTC
